### ISSUE TITLE
New errors emerge after upgrade to 0.4.0

### ISSUE THREAD

**Issue by jaraco** [businho/pytest-ruff#26]
With the 0.4.0 release of pytest-ruff, the Setuptools test suite has [started failing](https://github.com/pypa/setuptools/pull/4454#issuecomment-2218686349) on the TRY003 checks. Downgrading to `pytest-ruff 0.3.2` restores the previous behavior. I don't see anything in the [changelog](https://github.com/businho/pytest-ruff/compare/v0.3.2...v0.4.0) indicating why new checks would start failing.

Is it expected that previously passing checks are now failing with pytest-ruff 0.4?

**Comment by jaraco** [comment]
After a bit more examination. It seems the issue is multi-faceted. Setuptools recently added opt-in rules for TRY and ruff recently added support for TRY003 (the one that's failing). What I still don't understand is why the upgrade from pytest 0.3.2 to 0.4.0 caused these checks to start firing.

**Comment by Avasam** [comment]
https://github.com/pypa/setuptools/pull/4454#issuecomment-2218737317

> Btw @jaraco TRY003 isn't new at all, it's been there since [astral-sh/ruff@v0.0.236 (release)](https://github.com/astral-sh/ruff/releases/tag/v0.0.236) , and I don't see any mention of it since ruff 0.1 [astral-sh/ruff@main/CHANGELOG.md](https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md?rgh-link-date=2024-07-09T21%3A11%3A32Z)

> 
> My best guess is that pytest-ruff 0.4 did fix something that was hiding errors

> 
> @DimitriPapadopoulos 's https://github.com/pypa/setuptools/pull/4450 might've perfectly arrived as we started using Ruff 0.5 [pypa/setuptools/actions/runs/9724519803/job/26840815339#step:5:26](https://github.com/pypa/setuptools/actions/runs/9724519803/job/26840815339#step:5:26)

> 
> Ruff 0.5 wasn't compatible with pytest-ruff 0.3.2 apparently https://github.com/businho/pytest-ruff/issues/23 (not sure why in our case it silently passed instead of failing though). But that would explain why it passed the CI until some fixes in pytest-ruff 0.4

> 
> No idea how @DimitriPapadopoulos didn't get TRY003 locally, because I get it on setuptool's repo as far back as ruff 0.1.8 (maybe you ran through tox / pytest-ruff ? )

**Comment by DimitriPapadopoulos** [comment]
See https://github.com/businho/pytest-ruff/issues/22.

**Comment by jaraco** [comment]
Thanks everyone for jumping on this quickly and for clarifying the situation. I don't think there's anything else to be done here.
