### ISSUE TITLE
Build results in pytest_ruff-0.0.0.post672659.dev0+a9f2fde03404-py3-none-any.whl when sources are taken from GitHub

### ISSUE THREAD

**Issue by yurivict** [businho/pytest-ruff#30]
The version 0.0.0 is wrong in the wheel file.

pytest_ruff-0.4.1-py3-none-any.whl is built when the PYPI tarball is used.

**Comment by iurisilvio** [comment]
This project use `poetry-dynamic-versioning`. If you want to build it local, you can override the version with environment variables [documented here](https://github.com/mtkennerly/poetry-dynamic-versioning?tab=readme-ov-file#environment-variables): `POETRY_DYNAMIC_VERSIONING_BYPASS = "0.4.1"`
