### ISSUE TITLE
Bug: TypeError: format_file() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by boidolr** [businho/pytest-ruff#9]
Using pytest-ruff v0.2:
```
self = <RuffFormatItem ruff::format>

    def runtest(self):
>       self.handler(self.fspath)
E       TypeError: format_file() takes 1 positional argument but 2 were given
```

I think the issue is that we get passed `self` here: https://github.com/businho/pytest-ruff/blob/main/pytest_ruff.py#L98

**Comment by skellys** [comment]
I had the same issue in #7 and put up a bugfix PR here, but I found one case where behavior isn't intuitive (that one failing test): https://github.com/businho/pytest-ruff/pull/8

**Comment by iurisilvio** [comment]
Fixed by #8. 🙏🏻 

I was really interested in integrating ruff format and did a really bad release and didn't had time to make it work in my projects. 😞

**Comment by skellys** [comment]
glad i could help! cheers

**Comment by boidolr** [comment]
Thanks for the quick fix @skellys and @iurisilvio for providing this package :)
Also sorry for duplicating the issue.
